import type { Metadata } from 'next'
import { Sen } from 'next/font/google'
import './globals.css'

//Components
import Footer from '@/components/Footer'
import Header from '@/components/Header'

//Theme Provider
import { ThemeProvider } from '@/components/ThemeProvider'

const Josef = Sen({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Interior Website',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={Josef.className}>
        <ThemeProvider attribute='class' defaultTheme='light'>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
